CREATE DATABASE IF NOT EXISTS burgers_db;
use burgers_db;

CREATE TABLE IF NOT EXISTS burgers (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    burger_name VARCHAR(120),
    devoured BOOL DEFAULT FALSE
);